use_frameworks!

platform :ios, '9.0'

target 'SPUserCenterUIExtension_Example' do
  pod 'SPUserCenterUIExtension', :path => '../'

  target 'SPUserCenterUIExtension_Tests' do
    inherit! :search_paths

    
  end
end
